name: WTH Azure infrastructure
run-name: ${{ github.actor }} infrastructure provision

on: 
    workflow_dispatch:

jobs:
    infrastructure:
        name: azure infrastructure
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3.5.2    
          - name: Azure Login
            uses: Azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
          - name: Check variable
            run: echo ${{  vars.AZURE_RG_WTH  }}
