name: WTH GitHub workflow
run-name: ${{ github.actor }} is learning WTH

on: 
    workflow_dispatch:
    issues:
        types: [opened, edited, milestoned]

env:
    ROGUE_LEDER: Rogue one

jobs:
    job1:
        name: Job 1
        runs-on: ubuntu-latest
        steps:
        - name: Echo one
          run: echo "$ROGUE_LEDER reporting"
        - name: Echo two
          run: echo "Rogue two"

    job2:
        name: Job 2
        runs-on: ubuntu-latest
        steps:
            - name: Evil Cow
              uses: mscoutermarsh/cowsays-action@master
              with:
                  text: 'Where Are the Droids?'
                  color: 'red'
            - name: Planet
              run: echo "$PLANET"
        needs: job1
        env:
            PLANET: "Alderaan"